DROP SCHEMA IF EXISTS Students;
CREATE SCHEMA IF NOT EXISTS Students;
SET SCHEMA Students;

DROP TABLE IF EXISTS Journal;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Lectures;

CREATE TABLE Students (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(255),
  SURNAME VARCHAR(255),
  SEX VARCHAR(8),
  GROUPNUMBER INTEGER
);
CREATE TABLE Lectures (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  TOPIC VARCHAR(255),
  DURATION INTEGER
);
CREATE TABLE Journal (
  ID INTEGER PRIMARY KEY AUTO_INCREMENT,
  STUDENT_ID INTEGER,
  LECTURE_ID INTEGER,
  RECORD_DATE DATETIME,
  FOREIGN KEY (STUDENT_ID) REFERENCES Students(ID) ON DELETE CASCADE,
  FOREIGN KEY (LECTURE_ID) REFERENCES Lectures(ID) ON DELETE CASCADE
);