DELETE FROM Journal;
DELETE FROM Students;
DELETE FROM Lectures;

INSERT INTO Students (NAME, SURNAME, SEX, GROUPNUMBER) VALUES ('Ivan', 'Ivanov', 'MALE', 1);
INSERT INTO Students (NAME, SURNAME, SEX, GROUPNUMBER) VALUES ('Peter', 'Petrov', 'MALE', 1);
INSERT INTO Students (NAME, SURNAME, SEX, GROUPNUMBER) VALUES ('Sidor', 'Sidorov', 'MALE', 1);

INSERT INTO Lectures (TOPIC, DURATION) VALUES ('Sampling analysis', 90);
INSERT INTO Lectures (TOPIC, DURATION) VALUES ('Function analysis', 90);

INSERT INTO Journal (STUDENT_ID, LECTURE_ID, RECORD_DATE) VALUES (1, 1, '2016-12-28 09:00:00');
